name: Build and upload

on:
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
        buildtype: [debug, release]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          package-cache: true
          build-cache: true

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install -y \
            gcc-14 g++-14 

      - name: Configure (windows)
        if: runner.os == 'Windows'
        run: xmake config --toolchain=msvc -m ${{ matrix.buildtype }} -y -vv

      - name: Configure (linux)
        if: runner.os == 'Linux'
        run: xmake config --toolchain=gcc-14 -m ${{ matrix.buildtype }} -y -vv

      - name: Build
        run: xmake build -y -vv

      - name: Pack
        run: xmake pack -y -vv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.buildtype }}
          path: build/xpack