name: Build and upload

on:
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
        buildtype: [debug, release]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          package-cache: true
          build-cache: true

      - name: Configure
        run: xmake config -m ${{ matrix.buildtype }} -y -vv

      - name: Build
        run: xmake build -y -vv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.buildtype }}
          path: build/*/*/${{ matrix.buildtype }}/